---
title: "Query Databases and Data Frames in R with SQL"
output: html_notebook
---

```{r}
library(RSQLite)

fpath = ""
dbfile = "MediaDB.db"
dbcon <- dbConnect(RSQLite::SQLite(), paste0(fpath,dbfile))

sqlCmd = "SELECT * FROM invoice_items"

rs = dbGetQuery(dbcon, sqlCmd)
rs$ItemPrice <- rs$UnitPrice * rs$Quantity

round(mean(rs$ItemPrice, trim = 0.1), 2)
round
head(rs)
```

```{r}
library(sqldf)
rs2 <- sqldf("SELECT InvoiceId, SUM(ItemPrice) AS totalPrice, SUM(Quantity) AS itemNumber 
                FROM rs 
                GROUP BY InvoiceId;")
rs2
```

```{r}
library(ggplot2)

ggplot(data = rs2, aes(x = itemNumber, y = totalPrice)) + 
   stat_summary(geom = "line", fun.y = mean) + xlab("item number") + ylab("average price")
```

```{r}
result = tryCatch({
  query <- "SELECT DiscPrice FROM invoices"
  dbExecute(dbcon, query)
}, error = function(e){
  # If DiscPrice column not exist, add it.
  alter <- "ALTER TABLE invoices
                  ADD COLUMN DiscPrice 
                  NUMERIC(10, 2);"
  dbExecute(dbcon, alter)
}, finally = {
  # update values in DiscPrice
  update <- "UPDATE invoices
                SET DiscPrice = 
                CASE
                  WHEN InvoiceId IN
                    (SELECT InvoiceId AS invId 
                      FROM invoice_items
                      GROUP BY invId HAVING SUM(quantity) > 10)
                    THEN total * 0.9
                  ELSE total
                END;"
  dbExecute(dbcon, update)
})
```

```{r}
query <- "SELECT * FROM invoices;"
res <- dbGetQuery(dbcon, query)
res
dbDisconnect(dbcon)
```